### ISSUE TITLE
Error when clicking "Tabellenkonfiguration zurücksetzen"

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3334]
- go to https://dev.onegovgever.ch/fd/ordnungssystem/ressourcen-und-support/finanzen/allgemeines/dossier-425/
- click "Tabellenkonfiguration zurücksetzen"
- nothing/i.e. below error happens

https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3140/

```
AttributeError: 'DossierTabbedView' object has no attribute 'restrictedTraverse'
  File "ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "home/zope/eggs/ftw.tabbedview-3.8.3-py2.7.egg/ftw/tabbedview/browser/tabbed.py", line 201, in setgridstate
    listing_view = self._resolve_tab(view_name)
  File "home/zope/eggs/ftw.tabbedview-3.8.3-py2.7.egg/ftw/tabbedview/browser/tabbed.py", line 50, in _resolve_tab
    return self.context.restrictedTraverse(

AttributeError: 'DossierTabbedView' object has no attribute 'restrictedTraverse'
```

**Comment by phgross** [comment]
@deiferni can't reproduce this bug after an update on DEV, configuration_reset works fine for me. Please double check ...

**Comment by phabegger** [comment]
Ich habe das Problem eben auch bei gever-ftw. Wenn ich auf "Tabellenkonfiguration zurücksetzen" klicke, passiert nix. Siehe auch entsprechende Einträge in sentry. Ich kann es Dir sonst am Montag demonstrieren, @phgross

**Comment by deiferni** [comment]
@phgross i can no longer reproduce the issue on dev. the update seems to have fixed the problem. should we close?  also  i'll set sentry to solved in next release.

_(@phabegger in that case the issue should be fixed with the next release.)_

**Comment by phgross** [comment]
@deiferni 👍

**Comment by lukasgraf** [comment]
This wasn't really fixed as suspected. What ultimately solved this was fixing the base URL generation in #4686

**Comment by elioschmutz** [comment]
Changing the tabbedview-state on the personal_overview view is not possible which seems to be correct. If the user click on "Übersicht", it will work as expected. But if the user comes to the overview page through (i.e.) the notifications, the view will explicitly be called which will produce the error after updating the tabbedview-state:

![screen1](https://user-images.githubusercontent.com/557005/71259197-27237f80-2338-11ea-9947-df01cad22fbd.gif)
